spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: 'jdbc:mysql://localhost:3306/microservice-practice'
  jpa:
<<<<<<< Updated upstream
    generate-ddl: true
    show-sql: true
=======
    generate-ddl: false
    show-sql: false
default-pharmacy: quantum
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
>>>>>>> Stashed changes
